#!/bin/sh
lxsession &
# $HOME/scripts/vidbg && sleep 1 && picom --experimental-backend &
nitrogen --restore &
picom --experimental-backend &
volumeicon &
conky &
dunst &
xset s off -dpms
cbatticon -l 20 -r 10 &
# cmst &
