#!/usr/bin/env bash

# Two-phase filtering with Ripgrep and fzf
#
# 1. Search for text in files using Ripgrep
# 2. Interactively restart Ripgrep with reload action
#    * Press alt-enter to switch to fzf-only filtering
# 3. Open the file in Vim
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
INITIAL_QUERY="${*:-}"
IFS=: read -ra selected < <(
  FZF_DEFAULT_COMMAND="$RG_PREFIX $(printf %q "$INITIAL_QUERY")" \
  fzf --ansi \
      --color "hl:-1:underline,hl+:-1:underline:reverse" \
      --layout "reverse" \
      --border \
      --disabled --query "$INITIAL_QUERY" \
      --bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
      --bind "alt-enter:unbind(change,alt-enter)+change-prompt(filename > )+enable-search+clear-query" \
      --prompt 'word > ' \
      --delimiter : \
      --preview 'bat --style="numbers,header" --color=always {1} --highlight-line {2}' \
      --preview-window 'down,60%,border-rounded,+{2}+3/3,~3'
)

[ -n "${selected[0]}" ] && micro "${selected[0]}" "+${selected[1]}"
